// <auto-generated />
using System;
using CryptoGrimoire.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoGrimoire.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220916114631_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CryptoGrimoire.Models.Exchange", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BlogUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChatUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FeesUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TwitterAccountUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebSocketUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Name");

                    b.ToTable("Exchanges");

                    b.HasData(
                        new
                        {
                            Name = "Binance",
                            LongDesc = "Long Binance Description",
                            ShortDesc = "SBinD",
                            Url = "binance.com"
                        },
                        new
                        {
                            Name = "Bittrex",
                            LongDesc = "Long Bittrex Description",
                            ShortDesc = "SBitD",
                            Url = "bittrex.com"
                        },
                        new
                        {
                            Name = "Poloniex",
                            LongDesc = "Long Poloniex Description",
                            ShortDesc = "SPolD",
                            Url = "poloniex.com"
                        },
                        new
                        {
                            Name = "Bitfinex",
                            LongDesc = "Long Bitfinex Description",
                            ShortDesc = "SBitfD",
                            Url = "bitfinex.com"
                        },
                        new
                        {
                            Name = "HitBTC",
                            LongDesc = "Long HitBTC Description",
                            ShortDesc = "SHitD",
                            Url = "hitbtc.com"
                        },
                        new
                        {
                            Name = "Exmo",
                            LongDesc = "Long Exmo Description",
                            ShortDesc = "SExmD",
                            Url = "exmo.com"
                        });
                });

            modelBuilder.Entity("CryptoGrimoire.Models.ExchangeTradingPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(20,10)");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(20,10)");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(20,10)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(20,10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(20,10)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(20,10)");

                    b.HasKey("Id");

                    b.ToTable("ExchangeTradingPairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPrice = 41599m,
                            ExchangeName = "Binance",
                            High = 44153m,
                            LastPrice = 42252m,
                            Low = 41111m,
                            Name = "btc_usdt",
                            SellPrice = 42500m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7821),
                            Volume = 13546213m
                        },
                        new
                        {
                            Id = 2,
                            BuyPrice = 1349m,
                            ExchangeName = "Binance",
                            High = 1400m,
                            LastPrice = 1350m,
                            Low = 1300m,
                            Name = "eth_usdt",
                            SellPrice = 1350m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7857),
                            Volume = 646133m
                        },
                        new
                        {
                            Id = 3,
                            BuyPrice = 0.34m,
                            ExchangeName = "Binance",
                            High = 0.36m,
                            LastPrice = 0.35m,
                            Low = 0.33m,
                            Name = "xrp_usdt",
                            SellPrice = 0.35m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7862),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 4,
                            BuyPrice = 249m,
                            ExchangeName = "Binance",
                            High = 260m,
                            LastPrice = 250m,
                            Low = 240m,
                            Name = "bch_usdt",
                            SellPrice = 250m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7865),
                            Volume = 121351m
                        },
                        new
                        {
                            Id = 5,
                            BuyPrice = 119m,
                            ExchangeName = "Binance",
                            High = 130m,
                            LastPrice = 120m,
                            Low = 110m,
                            Name = "ltc_usdt",
                            SellPrice = 120m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7894),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 6,
                            BuyPrice = 41599m,
                            ExchangeName = "Bittrex",
                            High = 44153m,
                            LastPrice = 42252m,
                            Low = 41111m,
                            Name = "btc_usdt",
                            SellPrice = 42500m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7897),
                            Volume = 13546213m
                        },
                        new
                        {
                            Id = 7,
                            BuyPrice = 1349m,
                            ExchangeName = "Bittrex",
                            High = 1400m,
                            LastPrice = 1350m,
                            Low = 1300m,
                            Name = "eth_usdt",
                            SellPrice = 1350m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7899),
                            Volume = 646133m
                        },
                        new
                        {
                            Id = 8,
                            BuyPrice = 0.34m,
                            ExchangeName = "Bittrex",
                            High = 0.36m,
                            LastPrice = 0.35m,
                            Low = 0.33m,
                            Name = "xrp_usdt",
                            SellPrice = 0.35m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7902),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 9,
                            BuyPrice = 119m,
                            ExchangeName = "Bittrex",
                            High = 130m,
                            LastPrice = 120m,
                            Low = 110m,
                            Name = "ltc_usdt",
                            SellPrice = 120m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7904),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 10,
                            BuyPrice = 41599m,
                            ExchangeName = "Poloniex",
                            High = 44153m,
                            LastPrice = 42252m,
                            Low = 41111m,
                            Name = "btc_usdt",
                            SellPrice = 42500m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7907),
                            Volume = 13546213m
                        },
                        new
                        {
                            Id = 11,
                            BuyPrice = 1349m,
                            ExchangeName = "Poloniex",
                            High = 1400m,
                            LastPrice = 1350m,
                            Low = 1300m,
                            Name = "eth_usdt",
                            SellPrice = 1350m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7909),
                            Volume = 646133m
                        },
                        new
                        {
                            Id = 12,
                            BuyPrice = 0.34m,
                            ExchangeName = "Poloniex",
                            High = 0.36m,
                            LastPrice = 0.35m,
                            Low = 0.33m,
                            Name = "xrp_usdt",
                            SellPrice = 0.35m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7912),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 13,
                            BuyPrice = 41599m,
                            ExchangeName = "Bitfinex",
                            High = 44153m,
                            LastPrice = 42252m,
                            Low = 41111m,
                            Name = "btc_usdt",
                            SellPrice = 42500m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7914),
                            Volume = 13546213m
                        },
                        new
                        {
                            Id = 14,
                            BuyPrice = 1349m,
                            ExchangeName = "Bitfinex",
                            High = 1400m,
                            LastPrice = 1350m,
                            Low = 1300m,
                            Name = "eth_usdt",
                            SellPrice = 1350m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7917),
                            Volume = 646133m
                        },
                        new
                        {
                            Id = 15,
                            BuyPrice = 0.34m,
                            ExchangeName = "Bitfinex",
                            High = 0.36m,
                            LastPrice = 0.35m,
                            Low = 0.33m,
                            Name = "xrp_usdt",
                            SellPrice = 0.35m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7919),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 16,
                            BuyPrice = 249m,
                            ExchangeName = "Bitfinex",
                            High = 260m,
                            LastPrice = 250m,
                            Low = 240m,
                            Name = "bch_usdt",
                            SellPrice = 250m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7921),
                            Volume = 121351m
                        },
                        new
                        {
                            Id = 17,
                            BuyPrice = 41599m,
                            ExchangeName = "HitBTC",
                            High = 44153m,
                            LastPrice = 42252m,
                            Low = 41111m,
                            Name = "btc_usdt",
                            SellPrice = 42500m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7924),
                            Volume = 13546213m
                        },
                        new
                        {
                            Id = 18,
                            BuyPrice = 1349m,
                            ExchangeName = "HitBTC",
                            High = 1400m,
                            LastPrice = 1350m,
                            Low = 1300m,
                            Name = "eth_usdt",
                            SellPrice = 1350m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7926),
                            Volume = 646133m
                        },
                        new
                        {
                            Id = 19,
                            BuyPrice = 0.34m,
                            ExchangeName = "HitBTC",
                            High = 0.36m,
                            LastPrice = 0.35m,
                            Low = 0.33m,
                            Name = "xrp_usdt",
                            SellPrice = 0.35m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7928),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 20,
                            BuyPrice = 249m,
                            ExchangeName = "HitBTC",
                            High = 260m,
                            LastPrice = 250m,
                            Low = 240m,
                            Name = "bch_usdt",
                            SellPrice = 250m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7931),
                            Volume = 121351m
                        },
                        new
                        {
                            Id = 21,
                            BuyPrice = 119m,
                            ExchangeName = "HitBTC",
                            High = 130m,
                            LastPrice = 120m,
                            Low = 110m,
                            Name = "ltc_usdt",
                            SellPrice = 120m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7933),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 22,
                            BuyPrice = 41599m,
                            ExchangeName = "Exmo",
                            High = 44153m,
                            LastPrice = 42252m,
                            Low = 41111m,
                            Name = "btc_usdt",
                            SellPrice = 42500m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7935),
                            Volume = 13546213m
                        },
                        new
                        {
                            Id = 23,
                            BuyPrice = 1349m,
                            ExchangeName = "Exmo",
                            High = 1400m,
                            LastPrice = 1350m,
                            Low = 1300m,
                            Name = "eth_usdt",
                            SellPrice = 1350m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7938),
                            Volume = 646133m
                        },
                        new
                        {
                            Id = 24,
                            BuyPrice = 0.34m,
                            ExchangeName = "Exmo",
                            High = 0.36m,
                            LastPrice = 0.35m,
                            Low = 0.33m,
                            Name = "xrp_usdt",
                            SellPrice = 0.35m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7940),
                            Volume = 354513m
                        },
                        new
                        {
                            Id = 25,
                            BuyPrice = 1.01m,
                            ExchangeName = "Exmo",
                            High = 1.03m,
                            LastPrice = 1.015m,
                            Low = 1m,
                            Name = "usdt_usd",
                            SellPrice = 1.02m,
                            UpdatedDateTime = new DateTime(2022, 9, 16, 14, 46, 31, 154, DateTimeKind.Local).AddTicks(7943),
                            Volume = 45442445m
                        });
                });

            modelBuilder.Entity("CryptoGrimoire.Models.PageTradingPair", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("PageTradingPairs");

                    b.HasData(
                        new
                        {
                            Name = "btc_usdt",
                            Description = "btc to usdt"
                        },
                        new
                        {
                            Name = "eth_usdt",
                            Description = "eth to usdt"
                        },
                        new
                        {
                            Name = "xrp_usdt",
                            Description = "xrp to usdt"
                        },
                        new
                        {
                            Name = "bch_usdt",
                            Description = "bch to usdt"
                        },
                        new
                        {
                            Name = "ltc_usdt",
                            Description = "ltc to usdt"
                        },
                        new
                        {
                            Name = "usdt_usd",
                            Description = "usdt to usd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
